export enum MESSENGER_POSTBACK {
  GET_STARTED = 'GET_STARTED',
  SEARCH_BY_MERCHANT = 'SEARCH_BY_MERCHANT',
  SEARCH_BY_PRODUCT_LINK = 'SEARCH_BY_PRODUCT_LINK',
  WEEKLY_HOT_COUPON = 'WEEKLY_HOT_COUPON',
  SEARCH_HIGHLAND_COUPON = 'SEARCH_HIGHLAND_COUPON',
  TUTOTIAL = 'TUTOTIAL',
}
